### ISSUE TITLE
plugin does not work with sbt 1.4.6

### ISSUE THREAD

**Issue by francisdb** [otrebski/sbt-flaky#55]
addSbtPlugin("pl.otrebski" % "sbt-flaky" % "0.14")

```
[info] Updating
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/pl.otrebski/sbt-flaky/scala_2.12/sbt_1.0/0.14/ivys/ivy.xml
  100,0% [##########] 3,2 KiB (4,4 KiB / s)
https://repo1.maven.org/maven2/io/circe/circe-generic_2.12/0.8.0/circe-generic_2.12-0.8.0.pom
  100,0% [##########] 2,5 KiB (52,3 KiB / s)
https://repo1.maven.org/maven2/io/circe/circe-core_2.12/0.8.0/circe-core_2.12-0.8.0.pom
  100,0% [##########] 1,9 KiB (21,7 KiB / s)
https://repo1.maven.org/maven2/io/circe/circe-parser_2.12/0.8.0/circe-parser_2.12-0.8.0.pom
  100,0% [##########] 1,9 KiB (21,7 KiB / s)
https://repo1.maven.org/maven2/org/apache/commons/commons-vfs2/2.1/commons-vfs2-2.1.pom
  100,0% [##########] 11,1 KiB (125,0 KiB / s)
https://repo1.maven.org/maven2/com/lihaoyi/scalatags_2.12/0.6.5/scalatags_2.12-0.6.5.pom
  100,0% [##########] 2,6 KiB (15,7 KiB / s)
https://repo1.maven.org/maven2/org/apache/commons/commons-vfs2-project/2.1/commons-vfs2-project-2.1.pom
  100,0% [##########] 19,3 KiB (482,5 KiB / s)
https://repo1.maven.org/maven2/org/apache/commons/commons-parent/40/commons-parent-40.pom
  100,0% [##########] 62,6 KiB (1,3 MiB / s)
https://repo1.maven.org/maven2/io/circe/circe-jawn_2.12/0.8.0/circe-jawn_2.12-0.8.0.pom
  100,0% [##########] 1,9 KiB (45,5 KiB / s)
https://repo1.maven.org/maven2/io/circe/circe-numbers_2.12/0.8.0/circe-numbers_2.12-0.8.0.pom
  100,0% [##########] 2,0 KiB (46,2 KiB / s)
https://repo1.maven.org/maven2/org/typelevel/cats-core_2.12/0.9.0/cats-core_2.12-0.9.0.pom
  100,0% [##########] 4,5 KiB (104,3 KiB / s)
https://repo1.maven.org/maven2/com/github/mpilquist/simulacrum_2.12/0.10.0/simulacrum_2.12-0.10.0.pom
  100,0% [##########] 2,0 KiB (54,6 KiB / s)
https://repo1.maven.org/maven2/org/typelevel/cats-macros_2.12/0.9.0/cats-macros_2.12-0.9.0.pom
  100,0% [##########] 3,9 KiB (106,3 KiB / s)
https://repo1.maven.org/maven2/org/typelevel/machinist_2.12/0.6.1/machinist_2.12-0.6.1.pom
  100,0% [##########] 1,7 KiB (30,5 KiB / s)
https://repo1.maven.org/maven2/org/typelevel/cats-kernel_2.12/0.9.0/cats-kernel_2.12-0.9.0.pom
  100,0% [##########] 3,6 KiB (26,5 KiB / s)
[info] Resolved  dependencies
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-git:0.9.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-git/0.9.3/sbt-git-0.9.3.pom
[error]   not found: /Users/francisdb/.ivy2/local/com.typesafe.sbt/sbt-git/0.9.3/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/0.9.3/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-git/0.9.3/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3486)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-git:0.9.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-git/0.9.3/sbt-git-0.9.3.pom
[error]   not found: /Users/francisdb/.ivy2/local/com.typesafe.sbt/sbt-git/0.9.3/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/0.9.3/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-git/0.9.3/ivys/ivy.xml
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by PiotrBosak** [comment]
I know this thread is pretty old but recently I created a [fork](https://github.com/PiotrBosak/sbt-flaky) fixing this issue. It's not merged because I've removed most of the features from the original project but it does the most important thing and allows to run single test suites.
